version: "3.8"

services:
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client/:/usr/src/app/
    env_file:
      - .env.prod
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres:14-alpine
    ports:
      - "5434:5432"
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.db.prod

volumes:
  postgres_data: