version: "3.8"

services:
  client:
    container_name: client
    build: ./client
    volumes:
      - ./client/:/usr/src/app/
    env_file:
      - .env.dev
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres:14-alpine
    ports:
      - "5434:5432"
    expose:
      - "5432"
    env_file:
      - .env.db.dev
